### ISSUE TITLE
New feature needed

### ISSUE THREAD

**Issue by banujj** [theozgurr/NotificationMan#7]
1) repeat notification every week
2) open default app, when tapping notification

**Comment by 10zgurr** [comment]
1. this library only provides firing scheduled notifications not periodically. this can be achieved using the library with WorkManager's periodic work request. Please take a look at the details [here](https://developer.android.com/reference/androidx/work/PeriodicWorkRequest). 
2. you should provide the classpath you want to open when the notification is clicked.

<pre>NotificationMan
        .Builder(context = this, classPathWillBeOpen = "com.notification.man.MainActivity") // the activity's path that you want to open when the notification is clicked
        .setTitle(title = "test title") // optional
        .setDescription(desc = "test desc") // optional
        .setThumbnailUrl(thumbnailUrl = "image url") // optional
        .setTimeInterval(timeInterval = 10L) // needs secs - default is 5 secs
        .setNotificationType(type = NotificationTypes.IMAGE.type) // optional - default type is TEXT
        .setNotificationChannelConfig(config = createNotificationManChannelConfig()) // optional
        .fire()</pre> 

 Check this line:
<pre> .Builder(context = this, classPathWillBeOpen = "your_class_path_in_the_project.your_class_activity_name")</pre>
